server:
  port: 8081

spring:
  application:
    name: ha-hello
  resources:
    static-locations: classpath:/static/chart/
  thymeleaf:
    prefix: classpath:/static/chart/

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署