server:
  port: 8765

spring:
  profiles:
    active: test
  application:
    name: ha-hello
  resources:
    static-locations: classpath:/static/chart/
  thymeleaf:
    prefix: classpath:/static/chart/
  activemq:
    broker-url: tcp://60.205.94.149:61616
    user: admin
    password: admin
    pool:
      enabled: false

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    publisher-returns: true
    publisher-confirm-type: correlated

  datasource:
    database1:
      url: jdbc:mysql://127.0.0.1:3306/ewins?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true #数据库连接符
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
    database2:
      url: jdbc:mysql://192.168.1.21:3306/ewins?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true #数据库连接符
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
    #    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署